import os
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]
DOMAIN = "https://bhajan.ournakshatra.com"

def generate_sitemap():
    print("Generating perfect sitemap with clean canonical routes...")
    
    # Static base pages
    static_paths = [
        "/",
        "/index.html",
        "/bhajans.html",
        "/bhagavad-gita.html",
        "/shlokas.html",
        "/prayers.html",
        "/upanishads.html",
        "/wisdom.html",
        "/about.html",
        "/privacy-policy.html",
        "/contact.html",
        "/terms.html",
        "/disclaimer.html",
    ]
    
    urls = [DOMAIN + p for p in static_paths]
    
    # Clean SEO pages generated by generate_seo_pages.py
    seo_dirs = ["bhajan", "gita", "shloka", "prayer", "upanishad", "wisdom"]
    
    for d in seo_dirs:
        dir_path = ROOT / d
        if not dir_path.exists():
            continue
        for html_file in dir_path.rglob("index.html"):
            # Get the relative path starting from the SEO dir, e.g., bhajan/hanuman-chalisa/index.html
            rel_path = str(html_file.relative_to(ROOT))
            # Convert to clean URL: /bhajan/hanuman-chalisa/
            clean_url = "/" + rel_path.replace("index.html", "")
            urls.append(DOMAIN + clean_url)
            
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in sorted(set(urls)):
        # Calculate priority
        priority = "0.8"
        if url == DOMAIN + "/":
            priority = "1.0"
        elif url.endswith(".html"):
            priority = "0.9"
            
        lines.append("  <url>")
        lines.append(f"    <loc>{url}</loc>")
        lines.append(f"    <lastmod>{now}</lastmod>")
        lines.append("    <changefreq>weekly</changefreq>")
        lines.append(f"    <priority>{priority}</priority>")
        lines.append("  </url>")
        
    lines.append("</urlset>")
    
    (ROOT / "sitemap.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ Generated sitemap.xml with {len(urls)} perfect URLs.")

if __name__ == "__main__":
    generate_sitemap()
